import vip_fwd.types

// input relation VM_(vip: VIP)
// input relation FwdTable_(vip: VIP, ip: IP)
// input relation HostId(id: UUID)
// 
// output relation VM(vip: VIP, host: UUID) 
// output relation FwdTable(vip: VIP, ip: IP)

input relation VM_[VIP]
input relation FwdTable_[(VIP, IP)]
input relation HostId[UUID]

output relation VM[(VIP, UUID)]
output relation FwdTable[(VIP, IP)]

VM[(vip, host)] :- VM_[vip], HostId[host].
FwdTable[x] :- FwdTable_[x].
