import vip_fwd.types

// input relation VM_(vip: VIP)
// input relation FwdTable_(vip: VIP, ip: IP)
// input relation HostId(id: UUID)
// 
// output relation VM(vip: VIP, host: UUID) 
// output relation FwdTable(vip: VIP, ip: IP)

input relation VM_[bool]
input relation FwdTable_[(bool, bool)]
input relation HostId[bool]

output relation VM[(bool, bool)]
output relation FwdTable[(bool, bool)]

VM[(vip, host)] :- VM_[vip], HostId[host].
FwdTable[x] :- FwdTable_[x].
