import vip_fwd.types

// input relation VM_(vip: VIP)
// input relation FwdTable_(vip: VIP, ip: IP)
// input relation HostId(id: UUID)
// 
// output relation VM(vip: VIP, host: UUID) 
// output relation FwdTable(vip: VIP, ip: IP)

input relation VM[VIP]
input relation Forward_[(VIP, IP)]
input relation Host[UUID]

output relation VM_Host[(VIP, UUID)]
output relation Forward[(VIP, IP)]

VM_Host[(vip, host)] :- VM[vip], Host[host].
Forward[x] :- Forward_[x].
